[package]
org = "ballerina"
name = "json_schema_tool"
version = "0.1.0"
distribution = "2201.12.0"
keywords = ["json", "json schema", "json schema to record", "json-schema-tools"]
repository = "https://github.com/ballerina-platform/json-schema-tools"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
