[tool]
id = "jsonschema"

[[dependency]]
path = "../json-schema-cli/build/libs/json-schema-cli-1.0.3-SNAPSHOT.jar"

# [[dependency]]
# path = "../json-schema-core/build/libs/json-schema-core-1.0.3-SNAPSHOT.jar"

